# baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vacuum from Edward Vielmetti"
theme = "tale"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[menu]
  [[menu.main]]
    identifier = "Welcome"
    name = "Welcome"
    title = "Welcome"
    url = "/2021/0001-welcome/"
    weight = 1
  [[menu.main]]
    identifier = "subscribe"
    name = "Subscribe"
    title = "Subscribe"
    url = "https://groups.io/g/vacuum"
    weight = 2 
  [[menu.main]]
    identifier = "Github"
    name = "Github"
    title = "Github"
    url = "https://github.com/vielmetti/vacuum"
    weight = 3 
